#!/bin/bash

# OTP Console Demo - Shows what the console output looks like

echo ""
echo "🎬 DEMONSTRATION: Console OTP Output"
echo "================================================"
echo ""
echo "When you request a password reset, this is what appears in your console:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔐 PASSWORD RESET OTP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📧 Email: user@example.com"
echo "🔑 OTP Code: 456789"
echo "⏰ Valid for: 10 minutes"
echo "🕐 Generated: $(date '+%Y-%m-%d %H:%M:%S')"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ This appears AUTOMATICALLY in your terminal!"
echo "✅ Also saved to: storage/logs/otp.log"
echo "✅ No email configuration needed for development!"
echo ""
echo "================================================"
echo ""
echo "📝 To test:"
echo "   1. Go to: http://localhost/login/resetPassword"
echo "   2. Enter an email address"
echo "   3. Click 'Send OTP'"
echo "   4. Watch this console for the OTP!"
echo ""
echo "📁 To view log file:"
echo "   tail -f storage/logs/otp.log"
echo ""
